name    'ericsson-cgroups'
version '1.0.0'
source 'https://github.com/Ericsson/puppet-module-cgroups.git'
author 'ericsson'
license 'Apache License, Version 2.0'
summary 'manage cgroups functionality'
description 'manages cgroups configfile and cgroups service'
project_page 'https://github.com/Ericsson/puppet-module-cgroups'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
